import Link from "next/link";
import { ArrowRight, CalendarClock, IndianRupee, TrendingUp, Users } from "lucide-react";
import { listLeads } from "@/lib/leads";
import { readDemoDatabase } from "@/lib/demo-store";
import { isDemoMode } from "@/lib/env";
import { AdminHeading } from "@/components/admin/admin-heading";
import { LeadTable } from "@/components/admin/lead-table";

export default async function AdminDashboard(){const leads=await listLeads();const registered=leads.filter(lead=>lead.stage==="Registered").length;const due=leads.filter(lead=>lead.nextFollowUp&&new Date(lead.nextFollowUp)<=new Date("2026-08-08")).length;const payments=isDemoMode?(await readDemoDatabase()).payments.filter(item=>item.status==="paid").length:0;const metrics=[{label:"Active leads",value:leads.filter(l=>l.stage!=="Archived"&&l.stage!=="Lost").length,icon:Users,note:"current pipeline"},{label:"Registered",value:registered,icon:TrendingUp,note:"teams converted"},{label:"Follow-ups due",value:due,icon:CalendarClock,note:"through 8 Aug"},{label:"Payments recorded",value:payments,icon:IndianRupee,note:"demo workspace"}];return <div className="mx-auto max-w-7xl"><AdminHeading eyebrow="Operations overview" title="Tournament pipeline" description="Lead movement, follow-ups and registration health in one operational view." action={<Link href="/admin/leads" className="inline-flex items-center gap-2 text-sm font-bold text-[#313999]">All leads <ArrowRight aria-hidden="true" className="size-4"/></Link>}/><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,icon:Icon,note})=><div key={label} className="border bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-3 font-heading text-4xl text-[#081326]">{value}</p></div><span className="grid size-9 place-items-center rounded-md bg-[#313999]/10 text-[#313999]"><Icon aria-hidden="true" className="size-4"/></span></div><p className="mt-3 text-[11px] uppercase tracking-wider text-slate-400">{note}</p></div>)}</section><section className="mt-7"><div className="mb-4 flex items-end justify-between"><div><h2 className="text-2xl text-[#081326]">Recent leads</h2><p className="mt-1 text-xs text-slate-500">Most recently created enquiries</p></div></div><LeadTable leads={leads.slice(0,6)}/></section></div>}
