import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2, Circle, Clock3, Mail, MapPin, Users } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { getCaptainTeamOrNull } from "@/lib/teams";
import { Progress, ProgressLabel, ProgressValue } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";

export default async function CaptainDashboard() {
  const session=await requireRole("captain"); const team=await getCaptainTeamOrNull(session.userId);
  if (!team) {
    return <div className="mx-auto max-w-3xl"><p className="eyebrow text-[#8d672c]">Captain workspace</p><h1 className="mt-2 text-3xl text-[#081326] sm:text-4xl">Registration link pending.</h1><section className="mt-8 border bg-white p-7 shadow-sm sm:p-9"><AlertTriangle aria-hidden="true" className="size-7 text-amber-600"/><h2 className="mt-5 text-2xl text-[#081326]">Your account is active, but no team is linked yet.</h2><p className="mt-3 text-sm leading-7 text-slate-600">Ask the tournament organizer to resend the captain invitation for {session.email}. This usually means the sign-in succeeded before the team registration record was created or made visible.</p><a href={`mailto:onedreamgroup17@gmail.com?subject=Captain%20registration%20link%20needed&body=Please%20resend%20the%20captain%20invitation%20for%20${encodeURIComponent(session.email)}.`} className="mt-6 inline-flex items-center gap-2 rounded-md bg-[#313999] px-4 py-2.5 text-sm font-bold text-white"><Mail aria-hidden="true" className="size-4"/>Email organizer</a></section></div>;
  }
  const steps=[{label:"Company & team",complete:true,href:"/dashboard/team"},{label:"Players",complete:team.players.length>=2,href:"/dashboard/team"},{label:"Rules",complete:Boolean(team.rulesAcceptedAt),href:"/dashboard/rules"},{label:"Payment",complete:team.paymentStatus==="Paid",href:"/dashboard/payment"}]; const completion=steps.filter(step=>step.complete).length*25;
  return <div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#8d672c]">Captain workspace</p><h1 className="mt-2 text-3xl text-[#081326] sm:text-4xl">Welcome back, {session.name.split(" ")[0]}.</h1><p className="mt-2 text-sm text-slate-600">Complete your invited team registration in verified steps.</p></div><Badge variant="outline" className="border-[#d7aa54] bg-white px-3 py-2 text-[#6f501f]">{team.registrationStatus}</Badge></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><section className="border bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Team</p><h2 className="mt-2 text-3xl text-[#081326]">{team.name}</h2><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><MapPin aria-hidden="true" className="size-4"/>{team.company} · {team.city}</p></div><span className="grid size-11 place-items-center rounded-full bg-[#313999]/10 text-[#313999]"><Users aria-hidden="true" className="size-5"/></span></div><Progress value={completion} className="mt-8"><ProgressLabel>Registration progress</ProgressLabel><ProgressValue>{completion}%</ProgressValue></Progress><div className="mt-7 grid gap-3 sm:grid-cols-2">{steps.map(step=><Link href={step.href} key={step.label} className="flex items-center justify-between border p-4 hover:border-[#d7aa54]"><span className="flex items-center gap-3 text-sm font-semibold">{step.complete?<CheckCircle2 aria-hidden="true" className="size-5 text-emerald-600"/>:<Circle aria-hidden="true" className="size-5 text-slate-300"/>}{step.label}</span><ArrowRight aria-hidden="true" className="size-4 text-slate-400"/></Link>)}</div></section><aside className="grid gap-5"><div className="bg-[#081326] p-6 text-white"><p className="eyebrow text-[#d7aa54]">Next action</p><h2 className="mt-3 text-2xl">{!team.rulesAcceptedAt?"Review the rules":"Complete payment"}</h2><p className="mt-3 text-sm leading-6 text-white/60">{!team.rulesAcceptedAt?"Read and record acceptance of the displayed rules version.":"Review the confirmed amount and terms before paying."}</p><Link href={!team.rulesAcceptedAt?"/dashboard/rules":"/dashboard/payment"} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#d7aa54]">Continue <ArrowRight aria-hidden="true" className="size-4"/></Link></div><div className="border bg-white p-6"><Clock3 aria-hidden="true" className="size-5 text-[#313999]"/><h2 className="mt-4 text-xl text-[#081326]">Operational details</h2><p className="mt-2 text-sm leading-6 text-slate-500">Exact city date and venue are pending administrator confirmation. You will be notified when verified.</p></div></aside></div></div>;
}
