import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { PageHero } from "@/components/public/page-hero";
import { RegisterInterestLink } from "@/components/public/register-interest-link";
import { TOURNAMENT } from "@/lib/constants";

export default function CitiesPage() {
  return <><PageHero eyebrow="Host cities" title="Four city leagues. Two Goa places in each."><p>Choose the city where your corporate team wants to begin. Exact dates, venues and registration deadlines will appear only after confirmation.</p></PageHero><section className="section-pad bg-[#f7f3ea]"><div className="container-shell"><div className="grid gap-5 md:grid-cols-2">{TOURNAMENT.cities.map((city,index)=><Link key={city} href={`/cities/${city.toLowerCase()}`} className="group flex min-h-56 flex-col justify-between border border-slate-200 bg-white p-8 hover:border-[#d7aa54]"><div className="flex items-center justify-between"><MapPin aria-hidden="true" className="size-6 text-[#4048b5]"/><span className="font-mono text-xs text-slate-400">CITY 0{index+1}</span></div><div><h2 className="text-3xl text-[#081326]">{city}</h2><p className="mt-3 text-sm leading-6 text-slate-500">Corporate city league · seven-over cricket · top two progress to Goa</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#313999]">City details <ArrowRight aria-hidden="true" className="size-4 transition-transform group-hover:translate-x-1"/></span></div></Link>)}</div><div className="mt-10 flex flex-col items-start justify-between gap-5 border-t border-[#d7aa54]/50 pt-8 sm:flex-row sm:items-center"><p className="max-w-xl text-sm leading-6 text-slate-600">Ready to choose your city? Start with the short team enquiry and our operations team will confirm availability.</p><RegisterInterestLink /></div></div></section></>;
}
